export const METRIC_KEYS = {
  SJ: "SJ",
  CMJ: "CMJ",
  DJ: "DJ",
  ONE_RM_BENCH: "ONE_RM_BENCH",
  ONE_RM_SQUAT: "ONE_RM_SQUAT",
  ONE_RM_DEADLIFT: "ONE_RM_DEADLIFT",
  ASI_LEFT: "ASI_LEFT",
  ASI_RIGHT: "ASI_RIGHT",
  ASI_INDEX: "ASI_INDEX",
  F0: "F0",
  V0: "V0",
  BODY_WEIGHT: "BODY_WEIGHT",
  PEAK_POWER: "PEAK_POWER",
  MEAN_POWER: "MEAN_POWER",
  PEAK_VELOCITY: "PEAK_VELOCITY",
  MEAN_VELOCITY: "MEAN_VELOCITY",
  RSI: "RSI",
  ECCENTRIC_DURATION: "ECCENTRIC_DURATION",
  CONCENTRIC_DURATION: "CONCENTRIC_DURATION",
  FLIGHT_TIME: "FLIGHT_TIME",
  CONTACT_TIME: "CONTACT_TIME",
} as const;

export type MetricKey = (typeof METRIC_KEYS)[keyof typeof METRIC_KEYS];

export const METRIC_UNITS: Record<MetricKey, string> = {
  SJ: "cm",
  CMJ: "cm",
  DJ: "cm",
  ONE_RM_BENCH: "kg",
  ONE_RM_SQUAT: "kg",
  ONE_RM_DEADLIFT: "kg",
  ASI_LEFT: "%",
  ASI_RIGHT: "%",
  ASI_INDEX: "%",
  F0: "N",
  V0: "m/s",
  BODY_WEIGHT: "kg",
  PEAK_POWER: "W",
  MEAN_POWER: "W",
  PEAK_VELOCITY: "m/s",
  MEAN_VELOCITY: "m/s",
  RSI: "ms/ms",
  ECCENTRIC_DURATION: "ms",
  CONCENTRIC_DURATION: "ms",
  FLIGHT_TIME: "ms",
  CONTACT_TIME: "ms",
};

export const METRIC_LABELS: Record<MetricKey, string> = {
  SJ: "Squat Jump",
  CMJ: "Countermovement Jump",
  DJ: "Drop Jump",
  ONE_RM_BENCH: "1RM Press Banca",
  ONE_RM_SQUAT: "1RM Sentadilla",
  ONE_RM_DEADLIFT: "1RM Peso Muerto",
  ASI_LEFT: "Asimetría Izquierda",
  ASI_RIGHT: "Asimetría Derecha",
  ASI_INDEX: "Índice ASI",
  F0: "Fuerza Máxima Teórica",
  V0: "Velocidad Máxima Teórica",
  BODY_WEIGHT: "Peso Corporal",
  PEAK_POWER: "Pico de Potencia",
  MEAN_POWER: "Potencia Media",
  PEAK_VELOCITY: "Pico de Velocidad",
  MEAN_VELOCITY: "Velocidad Media",
  RSI: "Reactive Strength Index",
  ECCENTRIC_DURATION: "Duración Excéntrica",
  CONCENTRIC_DURATION: "Duración Concéntrica",
  FLIGHT_TIME: "Tiempo de Vuelo",
  CONTACT_TIME: "Tiempo de Contacto",
};

export const ASYMMETRY_ALERT_THRESHOLD = 15;
